name: places
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  build_runner: ^2.2.0
  google_maps_flutter: ^2.1.10
  google_maps_webservice: ^0.0.20-nullsafety.5
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  hive: ^2.2.3
  hive_flutter: 1.1.0
  hive_generator: ^2.0.0
  path_provider: ^2.0.11
  fluttericon: 2.0.0
  geolocator: ^9.0.1
  image_picker: ^1.0.1
  validatorless: ^1.2.1
  flutter_typeahead: ^4.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
  uses-material-design: true

